name: 'Release Changelog Builder'
description: 'A GitHub/Gitea action that builds release notes/changelog from PRs and commits, supporting multiple providers (GitHub, Gitea) with tag annotations and prefix/postfix messages'
author: 'ravenwolf.org'
branding:
  icon: 'award'
  color: 'green'
inputs:
  platform:
    description: 'Defines the platform the action is run on. Available options: [`github`, `gitea`, `local`, `git`]. Defaults to auto-detection from environment.'
    required: false
  token:
    description: 'Defines the token to use to execute the git API requests with, uses environment token by default'
    required: false
  repo:
    description: 'Defines the repository to create the changelog for (owner/repo or URL). Defaults to the current repository if not provided.'
    required: false
  from-tag:
    description: |
      Defines the previous tag to compare against. Supports special values:
      - `@latest-release`: resolves to the tag of the most recent published release
        (falls back to the previous tag with a warning on local git or if no release exists,
        or if the release tag is the same as to-tag).
      - `-N` (e.g. `-1`, `-2`): selects the tag N positions before to-tag in newest-first
        history (e.g. `-1` is equivalent to the default auto-detect behaviour).
    required: false
  to-tag:
    description: |
      Defines the new tag to compare to. Defaults to `@current`.
      - `@current` (default): use the tag the workflow is running under (from the git ref),
        or fall back to the most recent tag if not running on a tag event.
    required: false
    default: '@current'
  mode:
    description: 'Defines the mode used to retrieve the information. Available options: [`PR`, `COMMIT`, `HYBRID`]. Defaults to `PR`.'
    required: false
    default: 'PR'
  configuration:
    description: 'Defines the relative path to the configuration file.'
    required: false
  configuration-json:
    description: 'Defines the configuration json. If provided, will be preferred over `configuration`.'
    required: false
  ignore-pre-releases:
    description: 'Defines if the action will only use full releases to compare against (Only used if fromTag is not defined).'
    required: false
    default: 'false'
  fetch-tag-annotations:
    description: 'Defines if the action should fetch tag annotation messages'
    required: false
    default: 'false'
  prefix-message:
    description: 'Optional message to prepend to the generated changelog'
    required: false
  postfix-message:
    description: 'Optional message to append to the generated changelog'
    required: false
  include-open:
    description: 'Defines if the changelog should include open PRs'
    required: false
    default: 'false'
  fail-on-error:
    description: 'Defines if the action should result in a build failure, if an error was discovered'
    required: false
    default: 'false'
  verbose:
    description: 'Enable verbose debug logging. Also enabled when ACTIONS_STEP_DEBUG=true.'
    required: false
    default: 'false'
  skip-certificate-check:
    description: 'Skip TLS certificate verification for API calls (self-hosted instances).'
    required: false
    default: 'false'
  max-tags-to-fetch:
    description: 'Maximum number of tags to fetch when searching for tags. If a specified tag is not found in the initial batch, more tags will be fetched up to this limit. Defaults to 1000.'
    required: false
    default: '1000'
outputs:
  changelog:
    description: The built release changelog built from the merged pull requests
  contributors:
    description: A comma separated list of contributors (usernames) who contributed to the release
  pull-requests:
    description: A comma separated list of PR numbers that were merged
  tag-annotation:
    description: The tag annotation message if fetchTagAnnotations was enabled
  owner:
    description: Specifies the owner of the repository processed
  repo:
    description: Describes the repository name, which was processed
  from-tag:
    description: Defines the `fromTag` which describes the lower bound to process pull requests for
  to-tag:
    description: Defines the `toTag` which describes the upper bound to process pull request for
  failed:
    description: Defines if there was an issue with the action run, and the changelog may not have been generated correctly. [true, false]
runs:
  using: 'node20'
  main: 'dist/index.js'

